// ...existing code...
export type Software = {
  // ...existing properties...
  // certificationLevel : null = pas évalué, 1 = ok, 2 = Attention, 3 = Interdit
  certificationLevel?: 1 | 2 | 3 | null
  // ...existing properties...
}
